import "../styles/globals.css";
import {Inter} from "next/font/google";
import React from 'react'
import {TRPCReactProvider} from "@/trpc/react";
import {ConfigProvider} from "antd";
import zhCN from "antd/es/locale/zh_CN";
import 'dayjs/locale/zh-cn';
import {AntdRegistry} from '@ant-design/nextjs-registry';

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "有记Yonote",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
        <body className={inter.className} suppressHydrationWarning={true}>
        <AntdRegistry>

            <TRPCReactProvider>
                {children}
            </TRPCReactProvider>
        </AntdRegistry>

        </body>
        </html>
    );
}
