import "../styles/globals.css";
import {Inter} from "next/font/google";
import React from 'react'
import {TRPCReactProvider} from "@/trpc/react";
import 'dayjs/locale/zh-cn';
import {AntdRegistry} from '@ant-design/nextjs-registry';
import Link from "next/link";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "有记Yonote",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
        <body className={inter.className} suppressHydrationWarning={true}>
        <AntdRegistry>
            <TRPCReactProvider>
                {children}
                <div className={'flex items-center justify-center text-gray text-3 bg-#F5F7FB pb-20 w-100vw'}>ICP备案号：<Link
                    href={'http://beian.miit.gov.cn/ '}>
                    京ICP备2024064381号-1
                </Link></div>
            </TRPCReactProvider>
        </AntdRegistry>

        </body>
        </html>
    );
}
